const movieData =[
    {
        id: 1,
        title: "Extraction 2",
        category: "Hollywood",
        genre: "Action",
        description: "Back from the brink of death, commando Tyler Rake embarks on a dangerous mission to save a ruthless gangster's imprisoned family",
        release_date: "9 June 2023",
        director: "Sam Hargrave",
        distributed: "by Netflix",
        starring: "Chris Hemsworth, Golshifteh Farahani, Adam Bessa",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_RxHMaB1wDwGf1uORrluiZxNwiO75FAtTyw&s"
    },
    {
        id: 2,
        title: "Furiosa Mad-max",
        category: "Hollywood",
        genre: "Action",
        description: "Snatched from the Green Place of Many Mothers, young Furiosa gets caught in the crossfire of two tyrannical warlords; as the tyrants fight for dominance, Furiosa soon finds herself in a nonstop battle to make her way home.",
        release_date: " 23 May 2024",
        director: "George Miller",
        distributed: "by Warner Bros Pictures",
        starring: "Anya Taylor-Joy, Chris Hemsworth, Tom Burke, Alyla Browne",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDinYomYAVU5HR_3aCfKolzQOuBPvqqxX4Xg&s"
    },
    {
        id: 3,
        title: "Romeo and Juliet",
        category: "Hollywood",
        genre: "Romance",
        description: "The rivalry between Verona's two well-established families, the Capulets and the Montagues, affects the relationship of their children Romeo and Juliet.",
        release_date: "27 October 1996",
        director: "Baz Luhrmann",
        distributed: "by 20th Century Studios",
        starring: "Leonardo DiCaprio, Claire Danes, Brian Dennehy, John Leguizamo, Pete Postlethwaite, Paul Sorvino, Diane Venora",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSz4Z8qYHs-HiXi8gJos3gnYn4LM6kOK1mbg&s"
    },
    {
        id: 4,
        title: "After Everything",
        category: "Hollywood",
        genre: "Romance",
        description: "Author Hardin Scott travels to Portugal in an attempt to make Natalie forgive him for what he did to her.",
        release_date: "13 September 2023",
        director: "Castille Landon",
        distributed: "by Voltage Pictures",
        starring: "	Hero Fiennes Tiffin, Josephine Langford, Mimi Keene, Benjamin Mascolo, Louise Lombard, Stephen Moyer",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSLb0mf6DirxbfBh25YdBLhAoVz9vd52VUwQ&s"
    },
    {
        id: 5,
        title: "Heropanti",
        category: "Bollywood",
        genre: "Romance",
        description: "When Renu elopes with her lover, her father, Chowdhary, kidnaps Bablu, who knows Renu's whereabouts, along with two of his friends. But Bablu falls in love with Dimpy, Chowdhary's younger daughter.",
        release_date: "23 May 2014",
        director: " Sabbir Khan",
        distributed: "by UTV Motion Pictures",
        starring: "	Tiger Shroff, Kriti Sanon, Prakash Raj",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKTJlS-ymDwphYXKlK--3mCgzlF1zSChV_gw&s"
    },
    {
        id: 6,
        title: "ABCD",
        category: "Bollywood",
        genre: "Comedy",
        description: "Suresh and Vinnie are childhood friends who are passionate about dancing. They form a dance group but face many hurdles to participate in the Las Vegas dancing competition.",
        release_date: " 19 June 2015",
        director: "Remo D'Souza",
        distributed: "by UTV Motion Pictures",
        starring: "Prabhu Deva, Varun Dhawan, Shraddha Kapoor, Sushant Pujari, Lauren Gottlieb, Raghav Juyal, Punit Pathak, Dharmesh Yelande",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSII08upMj02bhXAGkwYFR9QNo6N9RBBYWDXg&s"
    },
    {
        id: 7,
        title: "Slum Dog Millionnaire",
        category: "Bollywood",
        genre: "Action",
        description: "A teenager from the slums of Mumbai becomes a contestant on the show 'Kaun Banega Crorepati?' When interrogated under suspicion of cheating, he revisits his past, revealing how he had all the answers.",
        release_date: "12 November 2008",
        director: "Danny Boyle",
        distributed: "by Pathé Distribution",
        starring: "Dev Patel, Freida Pinto, Madhur Mittal, Anil Kapoor, Irrfan Khan",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAcumzi4AxbrLLjF1JOx1rYfAC-TLB8JJc1g&s"
    },
    {
        id: 8,
        title: "RRR",
        category: "Bollywood",
        genre: "Action",
        description: "A fearless revolutionary and an officer in the British force, who once shared a deep bond, decide to join forces and chart out an inspirational path of freedom against the despotic rulers.",
        release_date: " 24 March 2022",
        director: "S. S. Rajamouli",
        distributed: "by Pen Studios (North India), Lyca Productions (Tamil Nadu), KVN Productions (Karnataka), HR Pictures (Kerala)",
        starring: "N. T. Rama Rao Jr., Ram Charan, Alia Bhatt, Ajay Devgn, Ray Stevenson, Alison Doody, Olivia Morris",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK7L-CbZ88fyf39hnmSxoZWN8EJ_Md9_IMtw&s"
    },
    {
        id: 9,
        title: "Brotherhood",
        category: "Nollywood",
        genre: "Action",
        description: "After years of fighting to survive on the streets of Lagos, two brothers fall on opposite sides of the law.",
        release_date: "23 September 2022",
        director: "Loukman Ali",
        distributed: "by Genesis Pictures",
        starring: "Falz, Tobi Bakre, Ronke Oshodi Oke, Boma Akpore, Sam Dede, Toni Tones, Basket Mouth",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs17_2WFBnHbdSmDiM837VYi3Q5qWrLyPJqA&s"
    },
    {
        id: 10,
        title: "King of Boys",
        category: "Nollywood",
        genre: "Action",
        description: "Her insatiable appetite for power drives Eniola, a businesswoman and philanthropist, into politics. As she is drawn into a struggle for power her criminal baggage will prove a heavy burden.",
        release_date: "20 October 2018",
        director: "Kemi Adetiba",
        distributed: "by Netflix",
        starring: "	Sola Sobowale, Adesua Etomi, Reminisce, Toni Tones, Jide Kosoko, Illbliss",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvWypYprfKtpbrDaB2K9FvJiBqYwogdS9ivw&s"
    },
    {
        id: 11,
        title: "Koto Orun",
        category: "Nollywood",
        genre: "Thriller",
        description: "Koto Orun was one of the epics and most watched movies then by Late Alhaji Yekinni Ajileye and his actors and actresses of Osogbo. The movie focused on the battles and how difficult life can be. This Ajileye movie was the real deal back then. The movie is full of mystery about the spiritual world",
        release_date: "1989",
        director: "Yekini Ajileye",
        distributed: "by Ajileye Films Production",
        starring: "Abija wara, Iyamileko, Koledowo, Oyiboyi, Alhaji Yekini Ajileye",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFmw3DGIQblPRUqtAWJj3Dtq-TIxu1G_YX9A&s"
    },
    {
        id: 12,
        title: "Texas Chainsaw Massacre",
        category: "Hollywood",
        genre: "Thriller",
        description: "A Texas ghost town comes face to face with Leatherface, a notorious serial killer who wears a human skin mask and settles for nothing but vengeance.",
        release_date: "October 1, 1974",
        director: "Tobe Hooper",
        distributed: "by Bryanston Distributing Company",
        starring: "Marilyn Burns, Paul A. Partain, Edwin Neal, Jim Siedow, Gunnar Hansen",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb3VYIJxvd8Nqfpm5X--gG1c9k1CQpIIbnJw&s"
    },
    {
        id: 13,
        title: "Hypnotic",
        category: "Hollywood",
        genre: "Thriller",
        description: "Determined to find his missing daughter, Detective Danny Rourke finds himself spiraling down a rabbit hole while investigating a series of reality-bending crimes. Aided by Diana Cruz, a gifted psychic, Rourke simultaneously pursues and is pursued by a lethal specter, the one man he believes holds the key to finding the girl.",
        release_date: "12 May 2023",
        director: "Robert Rodriguez",
        distributed: "by Ketchup Entertainment, Relativity Media",
        starring: "Ben Affleck, Alice Braga, J. D. Pardo, Hala Finley, Dayo Okeniyi, Jeff Fahey, Jackie Earle Haley, William Fichtner",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTooS87IlsiRwBEc347AKc0--hYrT7GVLRsKQ&s"
    },
    {
        id: 14,
        title: "Stree",
        category: "Bollywood",
        genre: "Thriller",
        description: "The people of Chanderi live under constant fear of Stree, the spirit of a woman who attacks men at night during festivals. Vicky, along with his friends, decides to unravel the mystery.",
        release_date: "31 August 2018 ",
        director: "Amar Kaushik",
        distributed: "by AA Films",
        starring: "Rajkummar Rao, Shraddha Kapoor, Pankaj Tripathi, Aparshakti Khurana, Abhishek Banerjee",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTns0qrVZy6bAnDdRbLwa9o5r-b5h0TY435lg&s"
    },
    {
        id: 15,
        title: "NH10",
        category: "Bollywood",
        genre: "Thriller",
        description: "While on a road trip, Meera and Arjun witness an honour killing committed by a powerful gangster, Satbir. However, the latter soon starts pursuing the couple to eliminate them.",
        release_date: "13 March 2015",
        director: "Navdeep Singh",
        distributed: "by Eros International",
        starring: "	Anushka Sharma, Neil Bhoopalam, Darshan Kumar, Deepti Naval",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLzpazQUjZpakMr_e7xqGMdXSPhNw3wMC19A&s"
    },
    {
        id: 16,
        title: "Alchemy of Souls",
        category: "K.Drama",
        genre: "Thriller",
        description: "A powerful sorceress in a blind woman's body encounters a man from a prestigious family, who wants her help to change his destiny.",
        release_date: "18 June 2022 ",
        director: "	Park Joon-hwa",
        distributed: "by Studio Dragon ",
        starring: "Lee Jae-wook, Jung So-min, Go Youn-jung, Hwang Min-hyun",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1MY7iDvsYBq1NKpZkknfntCGfUs4Ry_F7WA&s"
    },
    {
        id: 17,
        title: "Jumong",
        category: "K.Drama",
        genre: "Action",
        description: "The great contributions of Jumong to the Kokuryo Dynasty.",
        release_date: "15 May 2006",
        director: "Lee Joo-hwan",
        distributed: "by Chorokbaem Media",
        starring: "Song Il-kook, Han Hye-jin, Kim Seung-soo, Jun Kwang-ryul, Oh Yeon-soo",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjVgT8cp12BJO7nATZTMLWVQejHHpTW4DRDQ&s"
    },
    {
        id: 18,
        title: "Ballerina",
        category: "K.Drama",
        genre: "Action",
        description: "Grieving the loss of a best friend she could not protect, former bodyguard Ok-ju sets out to fulfil her dear friend's last wish: sweet, sweet revenge.",
        release_date: "5 October 2023",
        director: "Lee Chung-hyeon",
        distributed: "by Netflix",
        starring: "Jeon Jong-seo, Kim Ji-hoon, Park Yu-rim",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyqFib9YDPKSktjlIOtngZOy80WjKGcaAErw&s"
    },
    {
        id: 19,
        title: "Boys before Flower",
        category: "K.Drama",
        genre: "Romance",
        description: "Geum Jan Di gets a scholarship to the elite Shin Hwa High School. She is picked on by Gu Jun Pyo, one of the richest and most popular students, but soon Jun Pyo finds himself attracted to her.",
        release_date: "5 January 2009",
        director: "Jeon Ki-sang",
        distributed: "by Jeon Ki-sang",
        starring: "Koo Hye-sun, Lee Min-ho, Kim Hyun-joong, Kim Bum, Kim Joon",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQabWFzWHYcSwq6_o_8d2L2MHCS4P-L8mZpLg&s"
    },
    {
        id: 20,
        title: "Heartstrings",
        category: "K.Drama",
        genre: "Romance",
        description: "Heartstrings is a youth melodrama about love, friendship and dreams, set against the backdrop of a performing arts college",
        release_date: "June 29 - August 19, 2011",
        director: "Pyo Min-soo",
        distributed: "by JS Pictures",
        starring: "Park Shin-hye, Jung Yong-hwa",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXZWuf6DOUOdvVL-paqiX4JCfsS-MHuClCgw&s"
    },
    {
        id: 21,
        title: "Terminator 2",
        category: "Hollywood",
        genre: "Action",
        description: "When John, Sarah's 10-year-old son is attacked by T-1000, a new robot created by Skynet to destroy humanity, Terminator takes it upon himself to fight T-1000 to save John and the human race.",
        release_date: "3 July 1991",
        director: "James Cameron",
        distributed: "by TriStar Pictures, Columbia TriStar Films AB",
        starring: "Arnold Schwarzenegger, Linda Hamilton, Robert Patrick",
        imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRWPKqc74QiQtlWOwR8lkodHza67coiLdIS1ZulV836tDYR9jad"
    },
    {
        id: 22,
        title: "The Dark Knight",
        category: "Hollywood",
        genre: "Action",
        description: "Batman has a new foe, the Joker, who is an accomplished criminal hell-bent on decimating Gotham City. Together with Gordon and Harvey Dent, Batman struggles to thwart the Joker before it is too late.",
        release_date: "18 July 2008 ",
        director: "Christopher Nolan",
        distributed: "by Warner Bros., Warner Bros. Pictures, FilmFlex",
        starring: "Christian Bale, Michael Caine, Heath Ledger, Gary Oldman, Aaron Eckhart, Maggie Gyllenhaal, Morgan Freeman",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh7k6Lbp_Mkv2zpHphIG4JMSgc6qWfN_1bmP0TbHqIX42SPeUA"
    },
    {
        id: 23,
        title: "The Lord of the Rings",
        category: "Hollywood",
        genre: "Action",
        description: "The Lord of the Rings is a trilogy of epic fantasy adventure films directed by Peter Jackson, based on the novel The Lord of the Rings by English author J. R. R. Tolkien. The films are titled identically to the three volumes of the novel: The Fellowship of the Ring, The Two Towers, and The Return of the King.",
        release_date: "2001–2003",
        director: "Peter Jackson",
        distributed: "by New Line Cinema",
        starring: "Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Christopher Lee, Billy Boyd, Dominic Monaghan, Orlando Bloom, Hugo Weaving, Andy Serkis, Sean Bean",
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQzxpgGjFJrfZyw4i4Xhs27pUphAYzwnFTxOdVh0C72UpTOUmgi"
    },{
        id: 24,
        title: "Inception",
        category: "Hollywood",
        genre: "Action",
        description: "Cobb steals information from his targets by entering their dreams. He is wanted for his alleged role in his wife's murder and his only chance at redemption is to perform a nearly impossible task.",
        release_date: "8 July 2010",
        director: "Christopher Nolan",
        distributed: "by Warner Bros., Warner Bros. Pictures, Sandrew Metronome, Warner Bros. Entertainment France",
        starring: "Leonardo DiCaprio, Ken Watanabe, Joseph Gordon-Levit, Marion Cotillard, Elliot Page, Tom Hardy, Cillian Murphy, Tom Berenger, Michael Caine",
        imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSB56HndJ5CTFzAfx8Z9Apee3PJ4T4SGAulTzZIOq5zFG89F96D"
    },
    {
        id: 25,
        title: "Ip Man",
        category: "Hollywood",
        genre: "Action",
        description: "In 1930s China, a martial artist loses his home after the Imperial Japanese Army invades the country. With little means to survive, he must find a way to sustain his family.",
        release_date: " 12 December 2008 ",
        director: "Wilson Yip",
        distributed: "by Mandarin Films Distribution Co. Ltd.",
        starring: "	Donnie Yen, Simon Yam, Lynn Hung, Gordon Lam, Fan Siu-wong, Xing Yu, Chen Zhihui, Hiroyuki Ikeuchi, Tenma Shibuya",
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTsy5_DCLs_ktfTAaI5U27r4fUZ1g1tlTreLhq7bA98dPc-6yzV"
    },
    {
        id: 26,
        title: "John Wick",
        category: "Hollywood",
        genre: "Action",
        description: "John Wick is an American neo-noir action film series and media franchise created by Derek Kolstad. It centers on the titular character portrayed by actor Keanu Reeves. Wick is a legendary hitman who is reluctantly drawn back into the criminal underworld after retiring. ",
        release_date: "October 24, 2014",
        director: "Chad Stahelski[i",
        distributed: "by Summit Entertainment",
        starring: "Keanu Reeves, Michael Nyqvist, Alfie Allen, Adrianne Palicki, Bridget Moynahan, Dean Winters, Ian McShane, John Leguizamo, Willem Dafoe",
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT8cf_vso_9HUHwoTVE_gu65iERa_4OBctQvGFdVMWcMQcg8snX"
    },
    {
        id: 27,
        title: "Blade II",
        category: "Hollywood",
        genre: "Action",
        description: "A rare mutation gives birth to a new vampire community called the Reapers, who attack both humans and vampires. Blade, along with an elite vampire force, is asked to wipe out the Reaper's population.",
        release_date: "21 March 2002 ",
        director: "Guillermo del Toro",
        distributed: "by New Line Cinema, Warner Bros.",
        starring: "Wesley Snipes, Kris Kristofferson, Ron Perlman, Leonor Varela, Norman Reedus, Luke Goss",
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSVDhIkhJH9ogrVo7S4L-TSvzMdXTp5OE6_wtSMkV9FgUIWWhi0"
    },
    {
        id: 28,
        title: "Apocalyto",
        category: "Hollywood",
        genre: "Action",
        description: "Jaguar Paw, a young man, is captured by rulers of the Mayan kingdom. When they decide to sacrifice him, he makes a plan to escape death.",
        release_date: "8 December 2006 ",
        director: "Mel Gibson",
        distributed: "by Icon Productions, 20th Century Studios ·",
        starring: "Rudy Youngblood, Raoul Trujillo, Mayra Sérbulo, Dalia Hernández",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIR4O3aqe9F1GMttSbh1I4psOH-zVsUXmYPzhDy_G0Iua4k6ub"
    },
    {
        id: 29,
        title: "The Expendables 2",
        category: "Hollywood",
        genre: "Action",
        description: "All hell breaks loose when Barney, along with his band of old-school mercenaries, sets out on a path of carnage after one of their comrades gets killed during a simple task assigned by Mr. Church.",
        release_date: "15 August 2012",
        director: "Simon West",
        distributed: "by Starz Entertainment Corp., Lionsgate Films",
        starring: "Sylvester Stallone, Jason Statham, Jet Li, Dolph Lundgren, Chuck Norris, Jean-Claude Van Damme, Bruce Willis, Arnold Schwarzenegger, Terry Crews, Randy Couture, Liam Hemsworth, Scott Adkins, Yu Nan",
        imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS0_J5Em5QFy2kx7udUEJvSX-wY-g0t4yl8mvyyx7wTa5-CNbTU"
    },
    {
        id: 30,
        title: "Badland Hunters",
        category: "K.Drama",
        genre: "Action",
        description: "After a major earthquake, Seoul, South Korea, transforms into an apocalyptic wasteland where everything from civilization to law and order has collapsed.",
        release_date: " 26 January 2024",
        director: "Heo Myeong-haeng",
        distributed: "by Netflix",
        starring: "Ma Dong-seok, Lee Hee-joon, Lee Jun-young, Roh Jeong-eui",
        imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQfu8s58rrF8PRMR_tgl-OMJnd0IOGwekBRoWrtVfZtn9x687PE"
    },
    {
        id: 31,
        title: "Twisters",
        category: "Hollywood",
        genre: "Adventure",
        description: "Haunted by a devastating encounter with a tornado, Kate Cooper gets lured back to the open plains by her friend, Javi, to test a groundbreaking new tracking system. She soon crosses paths with Tyler Owens, a charming but reckless social-media superstar who thrives on posting his storm-chasing adventures. As storm season intensifies, Kate, Tyler and their competing teams find themselves in a fight for their lives as multiple systems converge over central Oklahoma.",
        release_date: "19 July 2024 ",
        director: "Lee Isaac Chung",
        distributed: "by Universal Pictures, Warner Bros. Pictures",
        starring: "Daisy Edgar-Jones, Glen Powell, Anthony Ramos, Brandon Perea, Maura Tierney, Sasha Lane",
        imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQpSoXKPxfIXdz1ZR0_LrZ9uEXdVl6wNaf9A-fj2dAIYK6pvlBM"
    },
    {
        id: 32,
        title: "Dune",
        category: "Hollywood",
        genre: "Action",
        description: "Paul Atreides arrives on Arrakis after his father accepts the stewardship of the dangerous planet. However, chaos ensues after a betrayal as forces clash to control melange, a precious resource.",
        release_date: "22 October 2021",
        director: "Denis Villeneuve",
        distributed: "by Warner Bros., Warner Bros. Pictures, SF Studios",
        starring: "Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Josh Brolin, Stellan Skarsgård, Dave Bautista, Stephen M. Henderson, Zendaya, Chang Chen, Sharon Duncan-Brewster, Charlotte Rampling, Jason Momoa, Javier Bardem",
        imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR1LLsjkzgNfod0aWCrpx6UECJqTuzufBKtD_PKe3daZr8XkrSu"
    },
    {
        id: 33,
        title: "Hit Man",
        category: "Hollywood",
        genre: "Thriller",
        description: "Professional killer Gary Johnson breaks protocol to help a desperate woman trying to flee an abusive husband and finds himself falling for her.",
        release_date: "24 May 2024",
        director: " Richard Linklater",
        distributed: "by Netflix",
        starring: "Glen Powell, Adria Arjona, Austin Amelio, Retta, Sanjay Rao",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqInif0K4t_iemSr1Kf_jkGO0fpyFaZ_Di8Bj1yvw-lsPe7hgP"
    },
    {
        id: 34,
        title: "The Fall Guy",
        category: "Hollywood",
        genre: "Romance",
        description: "After leaving the business one year earlier, battle-scarred stuntman Colt Seavers springs back into action when the star of a big studio movie suddenly disappears. As the mystery surrounding the missing actor deepens, Colt soon finds himself ensnared in a sinister plot that pushes him to the edge of a fall more dangerous than any stunt.",
        release_date: "3 May 2024",
        director: "David Leitch",
        distributed: "by Universal Pictures",
        starring: "Ryan Gosling, Emily Blunt, Aaron Taylor-Johnson, Hannah Waddingham, Teresa Palmer, Stephanie Hsu, Winston Duke",
        imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR9BvnBB450G5YVI3bgDQPWUmNwJegIT6NyBO7NUZe1Q8Y4p8w5"
    },
    {
        id: 35,
        title: "Anora",
        category: "Hollywood",
        genre: "Romance",
        description: "Anora, a sex worker from Brooklyn, gets her chance at a Cinderella story when she meets and marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as the parents set out for New York to get the marriage annulled.",
        release_date: "18 October 2024 ",
        director: "Sean Baker",
        distributed: "by Neon",
        starring: "Mikey Madison, Mark Eydelshteyn, Yura Borisov, Karren Karagulian, Vache Tovmasyan, Aleksei Serebryakov, Darya Ekamasova",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYNSKi80328-mySQG-o-YYL1ROp4vrvbQqUw&s"
    },
    {
        id: 36,
        title: "My Old Ass",
        category: "Hollywood",
        genre: "Romance",
        description: "An 18th-birthday mushroom trip brings Elliott face-to-face with her wisecracking 39-year-old self. When the older Elliott starts handing out warnings about what her younger self should and shouldn't do, she realizes she has to rethink everything about family, love, and what's becoming a transformative summer.",
        release_date: "20 January 2024",
        director: "Megan Park",
        distributed: "by Amazon MGM Studios",
        starring: "Maisy Stella, Percy Hynes White, Maddie Ziegler, Kerrice Brooks, Aubrey Plaza",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4H91zzwlbPhsk5ZYAxDV5VcH7JAcqBmvWdHOx_dIcS1lQbCag"
    },
    {
        id: 37,
        title: "Queer",
        category: "Hollywood",
        genre: "Romance",
        description: "Lee recounts his life in Mexico City among expatriate American students. He pursues a young man named Allerton, a US Navy serviceman recently discharged from Jacksonville, Florida.",
        release_date: "13 February 2025",
        director: "Luca Guadagnino",
        distributed: "by A24, Lucky Red",
        starring: "Daniel Craig, Drew Starkey, Jason Schwartzman, Henrique Zaga, Lesley Manville",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdtCtJPqtseuQiOMFvCF91L8c-S2Cu3oz8mnZfzc1DcTposmKJeCDk9lJnk_o9QmdviMo&usqp=CAU"
    },
    {
        id: 38,
        title: "Thelma",
        category: "Hollywood",
        genre: "Comedy",
        description: "Thelma Post is a 93-year-old grandmother who loses $10,000 to a con artist on the phone. With help from a friend and his motorized scooter, she soon embarks on a treacherous journey across Los Angeles to reclaim what was taken from her.",
        release_date: "21 June 2024",
        director: "Josh Margolin",
        distributed: "by Magnolia Pictures",
        starring: "June Squibb, Fred Hechinger, Richard Roundtree, Clark Gregg, Parker Posey, Malcolm McDowell",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxpl0jMVABNrVQrJKTlZvz8ndTZj6Lce6trc98mgQAVYprFyFy"
    },
    {
        id: 39,
        title: "The Idea of You",
        category: "Hollywood",
        genre: "Romance",
        description: "A 40-year-old single mum begins an unexpected romance with a 24-year-old boy band singer.",
        release_date: "16 March 2024",
        director: "Michael Showalter",
        distributed: "by Amazon Prime Video",
        starring: "Anne Hathaway, Nicholas Galitzine",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSu7Xka1qEa3yEaJLxAp3vcHMVHB-B9RCOoWDYxgwi4xcJaBOJz"
    },
    {
        id: 40,
        title: "Ajosepo",
        category: "Nollywood",
        genre: "Comedy",
        description: "A young couple must deal with all kinds of family tensions on the eve of their wedding.",
        release_date: "April 10, 2024",
        director: "Kayode Kasum",
        distributed: "by Film Trybe",
        starring: "Muyiwa Ademola, Tomike Adeoye, Mike Afolarin",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJUWvTBaplpXL6ciwd0AfHHJ4O3Qu_tYDGCfhrXn2c7BkUXxDc"
    },
    {
        id: 41,
        title: "Afamefuna",
        category: "Nollywood",
        genre: "Thriller",
        description: "After his friend is found dead, a prominent man is questioned by the police about their complex history together in the Igbo apprenticeship system.",
        release_date: "1 December 2023",
        director: "Kayode Kasum",
        distributed: "by Netflix",
        starring: "Stan Nze, Kanayo O. Kanayo, Alexx Ekubo, Segun Arinze",
        imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRGa_vLqb9UdSbSADLHJ43QAKK5rBHiqfVIKZM38IP5-khBCSLG"
    },
    {
        id: 42,
        title: "A Tribe called Judah",
        category: "Nollywood",
        genre: "Thriller",
        description: "Brothers plan to rob a small mall with their mother's help, but they are faced with armed robbers upon arriving.",
        release_date: "15 December 2023 ",
        director: " Funke Akindele, Adeoluwa Owu",
        distributed: "by FilmOne Distribution",
        starring: "Funke Akindele, Timini Egbuson, Jide Kene Achufusi, Uzee Usman, Tobi Makinde, Olumide Oworu",
        imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRzANLOvF4b4ZOB6WbUTU6vV5OJsabz0lca7Ze-Mds837aVTruG"
    },
    {
        id: 43,
        title: "A Green Fever",
        category: "Nollywood",
        genre: "Comedy",
        description: "A suave realtor and his sick daughter, in the aftermath of a medical emergency, seek refuge in a mysterious mansion, unraveling unsettling secrets in the middle of nowhere.",
        release_date: "9 November 2023",
        director: "Taiwo Egunjobi",
        distributed: "by Amazon Prime Video",
        starring: "William Chinoyenem, Temilolu Fosudo, Tobi Marho",
        imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQnkkTx9vBeEsAhkF-cqHSfTj-iw4f1tDEOwCOFyFBcP0XDO5ik"
    },
    {
        id: 44,
        title: "Gangs of Lagos",
        category: "Nollywood",
        genre: "Action",
        description: "When Obalola, Ify and Gift see their adoptive father murdered, they join a gang. With the start of election campaigns, the three friends are drawn into gang wars that drive them to fulfill their destiny.",
        release_date: "7 April 2023",
        director: "Jadesola Osiberu",
        distributed: "by Amazon Prime Video",
        starring: "Tobi Bakre, Adesua Etomi, Iyabo Ojo, Pasuma, Chike",
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR4w883PzB5j0a1OilPHPSDIQ1BJEvKEEygMw1QuJDT-41vlsSV"
    },
    {
        id: 45,
        title: "All is fair in love",
        category: "Nollywood",
        genre: "Romance",
        description: "Demi and Kanla's thriving business and friendship face a test when they both fall for Mbali, sparking a love triangle.",
        release_date: "February 14, 2024",
        director: "Kayode Kasum",
        distributed: "by Amazon Prime Video",
        starring: "Daniel Abua, Lateef Adedimeji, Venita Akpofure",
        imageUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQRGiyJOUIkpmLXxJuF-vz5XMg0GaG3txt8A8LBjJtSM7siQTL8"
    },
    {
        id: 46,
        title: "72 Hours: Martyr Who Never Died",
        category: "Bollywood",
        genre: "Action",
        description: "In a bid to defend the north-east front of India from the Chinese army, Jaswant Singh Rawat, a rifleman, combats the opponents alone for 72 hours.",
        release_date: "18 January 2019",
        director: "Avinash Dhyani",
        distributed: "by JSR Production House",
        starring: "	Avinash Dhyani, Mukesh Tiwari, Virendra Saxena, Alka Amin, Shishir Sharma, Gireesh Sahdev, Prashil Rawat",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvfeWTTzekJuXl3MP2yvkDhf8lZQbmpXpKLYc3x-gKGbNFUi5i"
    },
    {
        id: 47,
        title: "Pathaan",
        category: "Bollywood",
        genre: "Action",
        description: "A Pakistani general hires a private terror outfit to conduct attacks in India while Pathaan, an Indian secret agent, is on a mission to form a special unit.",
        release_date: "25 January 2023",
        director: "Siddharth Anand",
        distributed: "by Yash Raj Films",
        starring: "Shah Rukh Khan, Deepika Padukone, John Abraham, Dimple Kapadia, Ashutosh Rana",
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSYyWmO_Zfew93SUrdPAsxSV6G2v8pTwuE0YchSROAIHsPg6l8U"
    },
    {
        id: 48,
        title: "Kalki 2898 AD",
        category: "Bollywood",
        genre: "Action",
        description: "A modern avatar of the Hindu god Vishnu, is said to have descended on Earth to protect the world from evil forces.",
        release_date: "27 June 2024 ",
        director: "Nag Ashwin",
        distributed: "by Annapurna Studios",
        starring: "Amitabh Bachchan, Kamal Haasan, Prabhas, Deepika Padukone, Disha Patani, Shobana, Pasupathy, Anna Ben",
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTu6KOHuiPFgxLVAgQFitL_Y6uB0Vs426dWq0JT4KUmVVBTulTf"
    },
    {
        id: 49,
        title: "Yudhra",
        category: "Bollywood",
        genre: "Action",
        description: "A hotheaded ex-prisoner who is released on the condition of working with a drug cartel.",
        release_date: "20 September 2024",
        director: "Ravi Udyawar",
        distributed: "by AA Films",
        starring: "Siddhant Chaturvedi, Malavika Mohanan, Raghav Juyal",
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTjYdqbkhcwLSwO92UQuZZGrK3d4k3NCZzWbOhz3eeay_lg94dC"
    },
    {
        id: 50,
        title: "Unlocked",
        category: "K.Drama",
        genre: "Action",
        description: "A woman's life is turned upside-down after a dangerous man gets a hold of her lost cell phone and uses it to track her every move.",
        release_date: "17 February 2023",
        director: "Kim Tae-joon",
        distributed: "by Netflix, CJ ENM",
        starring: "Chun Woo-hee, Yim Si-wan, Kim Hee-won",
        imageUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcScBxkixNtsNA7klWjWD8JIkjyds0FCvPJv2mAm2hc6JqCOXSA6"
    },
]

export default movieData